

CD_str = "HUMIRA,PENTASA,REMICADE,ENTOCORT EC,ASACOL,LIALDA,IMURAN,AZATHIOPRINE,APRISO,CIMZIA,BUDESONIDE,CIPRO,MESALAMINE,HYOSCYAMINE,SULFASALAZINE,ASACOL HD,TOPAMAX,CIPROFLOXACIN,ENTYVIO,QUESTRAN,CHOLESTYRAMINE,LEVSIN,CANASA,BALSALAZIDE,INFLIXIMAB"

UC_str = "LIALDA,PREDNISONE,REMICADE,ASACOL,APRISO,MESALAMINE,AZATHIOPRINE,DELZICOL,IMURAN,SULFASALAZINE,HUMIRA,BALSALAZIDE,ASACOL HD,CANASA,PENTASA,UCERIS,COLAZAL,BUDESONIDE,AZULFIDINE,SIMPONI,SULFAZINE,ENTYVIO,HYDROCORTISONE,CATAPRES,CLONIDINE"

CD_list = CD_str.split(",")

UC_list = UC_str.split(",")




def read_file():
	str = ""
	with open("./genes_to_drugs.txt") as data:
		lines = [line.rstrip('\n') for line in data]
		for line in lines:
			if line[0:21] == "Unmatched search term":
				break
			if line[0:9] =="gene_name":
				str += line + '\tUC\tCD\n'
			else:
				str += line
				arr = line.split("\t")
				if len(arr) > 1:
					if arr[1] in CD_list:
						str += '\tfalse\ttrue\n'
					elif arr[1] in UC_list:
						str += '\ttrue\tfalse\n'
					else:
						str += '\tfalse\tfalse\n'
	return str

def write_file(x):
	efff = open("genes_to_drugs.txt", 'w')
	efff.write(x)
	efff.close()
	return

write_file(read_file())

'''
druglist
UC = [LIALDA,PREDNISONE,REMICADE,ASACOL,APRISO,MESALAMINE,AZATHIOPRINE,DELZICOL,IMURAN,SULFASALAZINE,HUMIRA,BALSALAZIDE,ASACOL HD,CANASA,PENTASA,UCERIS,COLAZAL,BUDESONIDE,AZULFIDINE,SIMPONI,SULFAZINE,ENTYVIO,HYDROCORTISONE,CATAPRES,CLONIDINE]
CD = [HUMIRA,PENTASA,REMICADE,ENTOCORT EC,ASACOL,LIALDA,IMURAN,AZATHIOPRINE,APRISO,CIMZIA,BUDESONIDE,CIPRO,MESALAMINE,HYOSCYAMINE,SULFASALAZINE,ASACOL HD,TOPAMAX,CIPROFLOXACIN,ENTYVIO,QUESTRAN,CHOLESTYRAMINE,LEVSIN,CANASA,BALSALAZIDE,INFLIXIMAB]
'''


